DROP DATABASE IF EXISTS empTrackerDB;
CREATE DATABASE empTrackerDB;

USE empTrackerDB;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 `name` VARCHAR(30) NOT NULL
);

CREATE TABLE `role` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL(10,3) NOT NULL,
    department_id INT NOT NULL FOREIGN KEY REFERENCES department(id)
);

CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  first_name  VARCHAR(30),
  last_name  VARCHAR(30),
  role_id  INT NOT NULL FOREIGN KEY REFERENCES `role`(id),
  manager_id  INT NULL FOREIGN KEY REFERENCES employee(id)
);